#' @title
#' Process NCI Thesaurus
#' OWL Files into Nodes and Edges
#'
#' @details
#' Processing occurs via Python and involves JSON intermediaries that are
#' written to the `tmp_neo4j` folder and unlinked on exit.
#'
#' @param owl_folder Path to the 'Thesaurus.owl' and 'ThesaurusInferred.owl' files downloaded
#' from the \href{https://evs.nci.nih.gov/ftp1/NCI_Thesaurus/}{NCI Thesaurus FTP}. An error will
#' be returned if both files cannot be found in the path and if both files are found, if the
#' NCI Thesaurus versions for both are not the same.
#'
#' @param output_folder Destination folder for the outputs generated by this function. Defaults to
#' `dev`.
#'
#' @return New node.csv, edge.csv, and nci_version.txt files in the output_folder/neo4j directory.
#'
#' @rdname process_owl_to_neo4j
#' @export
#' @import tidyverse
#' @import reticulate
#' @import cli
#' @importFrom glue glue

process_owl_to_neo4j <-
  function(owl_folder,
           output_folder = file.path(here::here(), "dev")) {


    cli::cli_h1("process_owl_to_neo4j")

    owl_folder <- path.expand(owl_folder)

    if (any(!(c("Thesaurus.owl","ThesaurusInferred.owl") %in% list.files(owl_folder)))) {


      cli::cli_abort(
        "Both Thesaurus.owl and ThesaurusInferred.owl must be found in {.var owl_folder}: {.file {owl_folder}}."
      )

    }


    # Creating a tmp_neo4j folder in dev/
    tmp_neo4j_folder <-
      file.path(
        output_folder,
        "tmp_neo4j")
    if (dir.exists(tmp_neo4j_folder)) {
      unlink(tmp_neo4j_folder,recursive = TRUE)
    }
    dir.create(path = tmp_neo4j_folder)
    # This tmp folder should be deleted on exit regardless
    # of error incurrence
    on.exit(unlink(tmp_neo4j_folder,recursive = TRUE))

    # Running Python script
    py_file <-
      system.file(package = "setupNCI", "py", "parse_ncit_owl.py")
    py_file_lines <-
      glue::glue(paste(readLines(py_file), collapse = "\n"),
                 .open = "{{{",
                 .close = "}}}"
      )
    py_run_string(py_file_lines)

    # Removing all contents in the dev/neo4j folder
    # to then be replaced with the newest nodes, edges, and nci_version
    # file
    neo4j_folder <-
      file.path(
        output_folder,
        "neo4j")
    file.remove(list.files(neo4j_folder, full.names = TRUE))

    # Adding newest version files to dev/neo4j
    target_files <-
      c("node.csv",
        "edge.csv",
        "nci_version.txt")
    tmp_target_files <-
      file.path(tmp_neo4j_folder,
                target_files)
    names(tmp_target_files) <-
      c("node",
        "edge",
        "nci_version")

    for (tmp_target_file in tmp_target_files) {

      R.utils::copyFile(
        tmp_target_file,
        neo4j_folder,
        overwrite = TRUE
      )

    }

    ####################### README ###########################
    # function that reads the nodes and edges csvs consistently
    # to produce a meaningful README

    read_file <-
      function(file) {
    readr::read_csv(file = file,
                    show_col_types = FALSE,
                    col_types = readr::cols(.default = "c"),
                    na = "NA") %>% # Blank values shouldn't be interpreted as NA_character__ in order to get accurate factor counts downstream
          dplyr::mutate_all(~tidyr::replace_na(.,"NULL")) # NA's are converted to NULLS (if they are present - likely not present)

      }

    # Reading newest version to include as part of the commit message
    nci_version <- readLines(tmp_target_files["nci_version"])

    # Adding summary of nodes file to README
    node <- read_file(file = tmp_target_files["node"])
    node_rows <- nrow(node)
    node_cols <- ncol(node)

    node_list <- as.list(node)
    node_list_sm <-
      node_list %>%
      purrr::map(
        function(x) forcats::fct_count(x, sort = TRUE, prop = TRUE)) # Unique values per field as a list of dataframes

    # Overwriting existing README file if it exists with header and some node
    # data
    readme_file <- file.path(neo4j_folder, "README.md")
    cat(
      glue::glue(
        "# Nodes and Edges  ",
        "Version {nci_version}  ",
        "---",
        "## Nodes  ",
        "Rows  : {node_rows}  ",
        "Fields: {node_cols}  ",
        .sep = "\n"
      ),
      file = readme_file)

    cat("\n",
        file = readme_file,
        sep = "  \n",
        append = TRUE)

    # Adding summary for each field in the node file
    for (i in seq_along(node_list_sm)) {

      cat(
        c(glue::glue("\n### {names(node_list_sm)[i]}  "),
          glue::glue("{nrow(node_list_sm[[i]])} x {ncol(node_list_sm[[i]])}  \n"),
          "  \n",
          tbl_to_gfm(node_list_sm[[i]] %>% dplyr::slice(1:10)),
          "\n"),
        file = readme_file,
        sep = "  \n",
        append = TRUE)


    }


    # Add Edge Summary to README like node above
    edge <- read_file(file = tmp_target_files["edge"])
    edge_rows <- nrow(edge)
    edge_cols <- ncol(edge)

    edge_list <- as.list(edge)
    edge_list_sm <-
      edge_list %>%
      purrr::map(
        function(x) forcats::fct_count(x, sort = TRUE, prop = TRUE))

    cat(
      glue::glue(
        "## Edges  ",
        "Rows  : {edge_rows}  ",
        "Fields: {edge_cols}  ",
        .sep = "\n"
      ),
      file = readme_file,
      append = TRUE)

    cat("\n",
        file = readme_file,
        sep = "  \n",
        append = TRUE)

    for (i in seq_along(edge_list_sm)) {

      cat(
        c(glue::glue("\n### {names(edge_list_sm)[i]}  "),
          glue::glue("{nrow(edge_list_sm[[i]])} x {ncol(edge_list_sm[[i]])}  \n"),
          "  \n",
          tbl_to_gfm(edge_list_sm[[i]] %>% dplyr::slice(1:10)),
          "\n"),
        file = readme_file,
        sep = "  \n",
        append = TRUE)


    }

    # Remove NCI version text file since version is now in README.md
    file.remove(file.path(neo4j_folder, "nci_version.txt"))

    # Add and commit newest version to repo
    system(glue::glue("git add {neo4j_folder}"))
    system(glue::glue("git commit -m 'bump version {nci_version} neo4j files'"))



    cli::cli_inform("{cli::symbol$tick} Version {nci_version} Nodes and Edges are now available at '{neo4j_folder}'")

  }
